version: "3.8"
services:
  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    container_name: postgres 
    volumes:
      - ./alphaheroes-back/alphaheroes-api/pgdata:/var/lib/postgresql/data 
    ports:
      - '5432:5432' 
  app: 
    build: 
      context: ./alphaheroes-back/alphaheroes-api/
      dockerfile: Dockerfile 
    container_name: nest-docker-postgres 
    environment: 
      - PORT=${PORT} 
    ports: 
      - '3000:3000' 
    depends_on: 
      - db 
    volumes:
      - ./alphaheroes-back/alphaheroes-api/src:/app/src 
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4 
    restart: always 
    container_name: nest-pgadmin4 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4 
    ports: 
      - '5050:80' 
    depends_on: 
      - db
  vite_docker:
    build:
      context: ./alphaheroes-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./alphaheroes-front/
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
    tty: true
volumes:
  node_modules: