@startuml name
title Project: Apprentissage de l'Alphabet

actor Enfant as User1
actor Parent as User2

component System {
  component Frontend {
    [React + TypeScript] as FrontendTech
  }
  component Backend {
    [Nest.js + Sequelize] as BackendTech
    component Database {
      [PostgreSQL] as DatabaseTech
    }
  }
}

User2 --> System : Se connecter

System --> User1 : Afficher l'interface utilisateur
System --> User2 : Afficher l'interface utilisateur

User1 --> System : Choisir un exercice
User2 --> System : Choisir un exercice pour l'enfant

System --> Backend : Récupérer l'exercice

Backend --> System : Envoyer l'exercice

User1 --> System : Réaliser l'exercice
User2 --> System : Suivre la progression de l'enfant

System --> Backend : Enregistrer les résultats

Backend --> System : Mettre à jour la progression

System --> User1 : Afficher les résultats
System --> User2 : Afficher la progression de l'enfant


User1 --> System : Se déconnecter
User2 --> System : Se déconnecter

note right of System
  Définir les objectifs d'apprentissage, le contenu et la progression
  Créer des illustrations et définir la charte graphique
  Mettre en œuvre la protection des données des utilisateurs et le contrôle d'accès
end note
@enduml
